### 03_accuracy_other_crops.mk
# Other crops accuracy evaluation → Table \ref{tab:other_crops}
SHELL := /bin/bash   # 'source' for conda activation needs bash, not dash
#
# The paper's table (accuracy_other_crops_adc_2022.tex, written to tables/) is
# generated by the AEF Hist Ensemble other-crops script, which also fixes the
# all-null histogram-row bug (2026-08-16). The legacy notebook wrote earlier
# versions to plots/ (no AEF Hist Ens. rows) and is kept only for reference —
# its plots/ outputs must NOT be copied to Overleaf.

CODE_DIR  := $(PROJ_DIR)/Code
TASK_DIR  := $(CODE_DIR)/analysis/03_accuracy_other_crops
TRAIN_DIR := $(CODE_DIR)/train/03_train_rf_gb

TABLES_DIR := $(DATA_DIR)/tables

.PHONY: accuracy_other_crops
accuracy_other_crops: $(TABLES_DIR)/accuracy_other_crops_adc_2022.tex

$(TABLES_DIR)/accuracy_other_crops_adc_2022.tex: $(TRAIN_DIR)/gb_aef_hist_ensemble_other_crops.py
	cd $(DATA_DIR) && $(ML_ENV) python3 $<

# Legacy notebook (superseded; mun-level table cut from the paper 2026-06-10)
.PHONY: accuracy_other_crops_legacy_nb
accuracy_other_crops_legacy_nb:
	cd $(DATA_DIR) && $(MPC_ENV) $(NB_EXEC) $(TASK_DIR)/1_accuracy_other_crops_2022.ipynb
