"""coauthor_extras_paper.py

Coauthor extras (1-4 plus drivers + irrig + corrected map) using the **paper's**
AEF Hist Ensemble predictions, with the same eval shape that produces
Within-R² = 0.152 / 0.154 (combined) and 0.163 / 0.164 (P-V) in
`accuracy_combined_2022.tex` / `accuracy_spring_summer_2022.tex`.

Differences from `coauthor_extras.py`:
  • predictions: `adc_aef_hist_ens_preds.parquet` (regenerated by
    `gb_aef_hist_ensemble.py`)
  • ground truth: keep ALL INEGI maize rows (no filter on land_input>0 or
    yield>0); do NOT dedupe by (adc, muncode) — there is one row per UP
  • additive correction uses `land_input` weights (planted area)
  • within-R² requires ≥2 ADCs per mun (not ≥5)
  • both raw and corrected predictions are evaluated

Outputs (under `Maize_prediction/plots/coauthor_extras_paper/`):
  fig1{a,b}_maize_share_vs_err_{combined,ss}.png
  fig2{a,b}_mun_vs_adc_err_{combined,ss}.png
  fig3{a-d}_within_r2_{state,mun}_{combined,ss}.png
  fig3{e,f}_within_r2_vs_irrig_{combined,ss}.png
  fig4_adc_yield_map.png                  (raw)
  fig4d_adc_yield_map_corrected.png       (additive-corrected)
  fig4b_adc_yield_map_inegi.png           (observed)
  fig4c_adc_yield_compare.png             (3-panel)
  fig5{a,b}_within_r2_drivers_{scatter,binned}.png
  summary_stats.txt
"""

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm

mpl.rcParams.update({"font.family": "serif",
                      "axes.titlesize": 12, "axes.labelsize": 11,
                      "xtick.labelsize": 9, "ytick.labelsize": 9,
                      "legend.fontsize": 9, "figure.dpi": 130})

# ── Directories ──────────────────────────────────────────
home_dir   =  os.path.expanduser("~")
proj_dir   =  os.path.join(home_dir, "Dropbox", "Projects", "Maize_prediction")
data_dir   =  os.path.join(proj_dir, "Data")
preds_dir  =  os.path.join(data_dir, "predictions")
out_dir    =  os.path.join(proj_dir, "plots", "coauthor_extras_paper")
os.makedirs(out_dir, exist_ok=True)

inegi_dir  =  os.path.join(data_dir, "INEGI", "MD_lab_outputs",
                            "LM2304-CA22-2025-09-29-superficie_ENTREGA")
sciaga_dir =  os.path.join(home_dir, "Dropbox", "Projects",
                            "Crop_misallocation", "Data")
siap_pkg   =  os.path.join(home_dir, "Dropbox", "Projects",
                            "Maize_prediction", "Data", "SIAP", "Cleaned")

pred_path   =  os.path.join(preds_dir, "adc_aef_hist_ens_preds.parquet")
eval_path   =  os.path.join(preds_dir, "adc_aef_hist_ens_eval.parquet")
gt_comb     =  os.path.join(inegi_dir, "adc_land_use_ca22_adc07.dta")
gt_szn      =  os.path.join(inegi_dir, "adc_land_szn_ca22_adc07.dta")
agland_csv  =  os.path.join(data_dir, "SIAP_agland", "Output",
                             "2007_adcs_agland_area.csv")
# Paper uses by-season SIAP for training but ca2007 for mun yield context
siap_ca07   =  os.path.join(siap_pkg, "siap_ag_prod_estimation_ca2007.dta")
siap_szn    =  os.path.join(siap_pkg, "siap_ag_prod_estimation_by_season.dta")
adc_shp     =  os.path.join(home_dir, "Dropbox", "Projects", "Maize_prediction",
                            "Data", "Shapefiles", "adc_shapefile.shp")
state_shp   =  os.path.join(sciaga_dir, "Municipality_shp", "STATES.shp")
mun_shp     =  os.path.join(data_dir, "SIAP_agland", "Output", "agland_mun16.shp")

YEAR              =  2022
MIN_ADCS_FOR_R2   =  2     # paper convention
MIN_ADCS_STATE    =  50
R2_CLIP_LO        =  -2.0

# ────────────────────────────────────────────────────────
# Eval helpers (match paper's exact procedure)
# ────────────────────────────────────────────────────────
def r2(y, yh):
    m  =  np.isfinite(y) & np.isfinite(yh)
    y, yh  =  np.array(y[m]), np.array(yh[m])
    if len(y) < 2: return np.nan
    st  =  np.sum((y - y.mean()) ** 2)
    return 1 - np.sum((y - yh) ** 2) / st if st > 0 else np.nan

def within_r2(df, y, p, gc="muncode"):
    s  =  df[[y, p, gc]].replace([np.inf, -np.inf], np.nan).dropna().copy()
    c  =  s.groupby(gc).size()
    s  =  s[s[gc].isin(c[c >= MIN_ADCS_FOR_R2].index)]
    if len(s) == 0: return np.nan
    gm  =  s.groupby(gc)[[y, p]].transform("mean")
    return r2(s[y] - gm[y], s[p] - gm[p])

def between_r2(df, y, p, gc="muncode"):
    s  =  df[[y, p, gc]].replace([np.inf, -np.inf], np.nan).dropna()
    g  =  s.groupby(gc)[[y, p]].mean()
    return r2(g[y], g[p])

# ────────────────────────────────────────────────────────
# Load paper-aligned eval frame (one row per INEGI maize UP)
# ────────────────────────────────────────────────────────
print(f"Loading paper eval frame: {eval_path}")
df  =  pd.read_parquet(eval_path)
print(f"  rows: {len(df):,}")
print(f"  N nonnull pred: {df['pred'].notna().sum():,}  "
      f"corr: {df['pred_corr'].notna().sum():,}")

print("\nReplicating paper accuracy rows:")
for ycol, label_y in [("yield", "Combined"), ("yield_pv", "Spring-Summer")]:
    d  =  df[df[ycol].notna()].copy() if ycol == "yield_pv" else df
    for pcol, plabel in [("pred", "Raw"), ("pred_corr", "Corr.")]:
        s  =  d[[ycol, pcol, "muncode"]].replace([np.inf, -np.inf], np.nan).dropna()
        N  =  len(s)
        Ov =  r2(s[ycol], s[pcol])
        B  =  between_r2(s, ycol, pcol)
        W  =  within_r2(s, ycol, pcol)
        RM =  np.sqrt(((s[ycol] - s[pcol]) ** 2).mean())
        print(f"  {label_y:<14s} {plabel:<6s} "
              f"N={N:>7,}  R²={Ov:.3f}  B={B:.3f}  W={W:.3f}  RMSE={RM:.3f}")

# adcid-level: get one prediction per adc (drop duplicates) for mapping
pred_adc  =  pd.read_parquet(pred_path)
print(f"\nADC-level predictions: {len(pred_adc):,}, "
      f"{pred_adc.adcid.nunique():,} unique adcs")

# Build adc12 (12-char no-hyphen) for joining with INEGI adc
pred_adc["adc"]  =  pred_adc["adcid"].str.replace("-", "", regex=False)

# ────────────────────────────────────────────────────────
# Per-ADC error frames (combined + SS)
# ────────────────────────────────────────────────────────
df["err_raw"]   =  df["pred"]      - df["yield"]
df["err_corr"]  =  df["pred_corr"] - df["yield"]
df["err_raw_pv"]   =  df["pred"]      - df["yield_pv"]
df["err_corr_pv"]  =  df["pred_corr"] - df["yield_pv"]
df["state"]  =  df["muncode"].str[:2]

# ────────────────────────────────────────────────────────
# Task 1: maize share (SIAP) vs ADC pred error
# ────────────────────────────────────────────────────────
print("\n=== Task 1: maize share vs ADC pred err ===")
siap  =  pd.read_stata(siap_ca07)
siap_22  =  siap[siap["year"] == YEAR].copy()
siap_22["is_maize"]  =  siap_22["name"].astype(str).str.lower().eq("maize")
siap_22["maize_ha"]  =  np.where(siap_22["is_maize"], siap_22["ha_planted"], 0.0)
mun_share  =  (siap_22.groupby("muncode", as_index=False)
                       .agg(maize_ha=("maize_ha", "sum"),
                            total_ha=("ha_planted", "sum"),
                            siap_q_maize=("q",
                                lambda s: s[siap_22.loc[s.index, "is_maize"]].sum())))
mun_share["maize_share"]      =  mun_share["maize_ha"] / mun_share["total_ha"]
mun_share["siap_yield_maize"] =  (mun_share["siap_q_maize"]
                                    / mun_share["maize_ha"].replace(0, np.nan))

def plot_t1(ycol, pcol_err, title, fname):
    d  =  df[df[ycol].notna() & df[pcol_err].notna()].copy()
    d  =  d.merge(mun_share[["muncode", "maize_share"]], on="muncode", how="left")
    d  =  d[d["maize_share"].notna()]
    d["abs_err"]  =  d[pcol_err].abs()
    bins  =  np.linspace(0, 1, 11)
    d["bin"]  =  pd.cut(d["maize_share"], bins, include_lowest=True)
    agg  =  (d.groupby("bin", observed=True)
               .agg(n=(pcol_err, "size"),
                    mean_abs=("abs_err", "mean"),
                    mean_signed=(pcol_err, "mean"))
               .reset_index())
    agg["x"]  =  agg["bin"].apply(lambda b: 0.5 * (b.left + b.right))
    r_abs  =  d[["maize_share", "abs_err"]].corr().iloc[0, 1]
    r_sig  =  d[["maize_share", pcol_err]].corr().iloc[0, 1]
    rho    =  d[["maize_share", "abs_err"]].corr(method="spearman").iloc[0, 1]
    fig, ax  =  plt.subplots(1, 2, figsize=(11, 4.2))
    ax[0].bar(agg["x"], agg["mean_abs"], width=0.085, color="#4a4a4a",
               edgecolor="white")
    ax[0].set_xlabel("Municipality maize share (SIAP)")
    ax[0].set_ylabel("Mean |ADC pred − INEGI| (t/ha)")
    ax[0].set_title(f"{title}: |err| vs maize share\n"
                     f"r = {r_abs:+.3f}, ρ = {rho:+.3f}, N = {len(d):,}")
    ax[1].axhline(0, color="grey", lw=0.6)
    ax[1].bar(agg["x"], agg["mean_signed"], width=0.085,
               color=["#c44e52" if v > 0 else "#3a78b0" for v in agg["mean_signed"]],
               edgecolor="white")
    ax[1].set_xlabel("Municipality maize share (SIAP)")
    ax[1].set_ylabel("Mean signed err (t/ha)")
    ax[1].set_title(f"{title}: signed err\n"
                     f"r(signed) = {r_sig:+.3f}")
    plt.tight_layout()
    fig.savefig(os.path.join(out_dir, fname), bbox_inches="tight", dpi=140)
    plt.close(fig)
    return {"r_abs": r_abs, "spearman_abs": rho, "r_signed": r_sig,
            "n": len(d)}

t1  =  {}
t1["raw_comb"]   =  plot_t1("yield",    "err_raw",
                              "Combined (raw)",          "fig1a_t1_combined_raw.png")
t1["corr_comb"]  =  plot_t1("yield",    "err_corr",
                              "Combined (corrected)",    "fig1a_t1_combined_corr.png")
t1["raw_pv"]     =  plot_t1("yield_pv", "err_raw_pv",
                              "P-V (raw)",              "fig1b_t1_ss_raw.png")
t1["corr_pv"]    =  plot_t1("yield_pv", "err_corr_pv",
                              "P-V (corrected)",        "fig1b_t1_ss_corr.png")

# ────────────────────────────────────────────────────────
# Task 2: mun-error vs ADC-error correlation
# ────────────────────────────────────────────────────────
print("\n=== Task 2: mun-err vs ADC-err ===")
agland  =  pd.read_csv(agland_csv)
agland["muncode"]  =  agland["adcid"].str[:5]

def plot_t2(ycol, pcol, pcol_err, title, fname):
    d  =  df[df[ycol].notna() & df[pcol].notna()].copy()
    # mun-level: planted-area-weighted mean of preds & obs (paper convention)
    d["wQp"]  =  d[pcol] * d["land_input"]
    d["wQy"]  =  d[ycol] * d["land_input"]
    d["wW"]   =  d["land_input"].fillna(0)
    m  =  (d.groupby("muncode")
             .agg(wQp=("wQp", "sum"), wQy=("wQy", "sum"), wW=("wW", "sum"))
             .reset_index())
    m["mun_pred"]  =  m["wQp"] / m["wW"]
    m["mun_obs"]   =  m["wQy"] / m["wW"]
    m["mun_err"]   =  m["mun_pred"] - m["mun_obs"]
    m  =  m.merge(mun_share[["muncode", "siap_yield_maize"]],
                    on="muncode", how="left")
    m["mun_err_siap"]  =  m["mun_pred"] - m["siap_yield_maize"]
    d  =  d.merge(m[["muncode", "mun_err", "mun_err_siap"]],
                    on="muncode", how="left")
    r_inegi   =  d[[pcol_err, "mun_err"]].corr().iloc[0, 1]
    r_siap    =  d[[pcol_err, "mun_err_siap"]].corr().iloc[0, 1]
    rho_inegi =  d[[pcol_err, "mun_err"]].corr(method="spearman").iloc[0, 1]
    fig, ax  =  plt.subplots(1, 2, figsize=(11, 4.5))
    lim  =  max(abs(d[pcol_err].quantile(0.005)),
                 abs(d[pcol_err].quantile(0.995)),
                 abs(d["mun_err"].quantile(0.005)),
                 abs(d["mun_err"].quantile(0.995)))
    ax[0].scatter(d["mun_err"], d[pcol_err], s=2, alpha=0.12,
                   color="#4a4a4a", rasterized=True)
    ax[0].plot([-lim, lim], [-lim, lim], "--", color="#c44e52", lw=0.8)
    ax[0].set_xlim(-lim, lim); ax[0].set_ylim(-lim, lim)
    ax[0].axhline(0, color="grey", lw=0.4); ax[0].axvline(0, color="grey", lw=0.4)
    ax[0].set_xlabel("Mun err (planted-wtd ADC pred − obs, INEGI)")
    ax[0].set_ylabel("ADC err (pred − INEGI)")
    ax[0].set_title(f"{title}: vs INEGI mun agg\n"
                     f"r = {r_inegi:+.3f}, ρ = {rho_inegi:+.3f}, N = {len(d):,}")
    d2  =  d[d["mun_err_siap"].notna()]
    ax[1].scatter(d2["mun_err_siap"], d2[pcol_err], s=2, alpha=0.12,
                   color="#4a4a4a", rasterized=True)
    ax[1].plot([-lim, lim], [-lim, lim], "--", color="#c44e52", lw=0.8)
    ax[1].set_xlim(-lim, lim); ax[1].set_ylim(-lim, lim)
    ax[1].axhline(0, color="grey", lw=0.4); ax[1].axvline(0, color="grey", lw=0.4)
    ax[1].set_xlabel("Mun err vs SIAP yield")
    ax[1].set_ylabel("ADC err (pred − INEGI)")
    ax[1].set_title(f"{title}: vs SIAP\nr = {r_siap:+.3f}, N = {len(d2):,}")
    plt.tight_layout()
    fig.savefig(os.path.join(out_dir, fname), bbox_inches="tight", dpi=150)
    plt.close(fig)
    return {"r_inegi": r_inegi, "r_siap": r_siap, "rho_inegi": rho_inegi,
            "n": len(d)}

t2  =  {}
t2["raw_comb"]   =  plot_t2("yield",    "pred",      "err_raw",
                              "Combined (raw)", "fig2a_t2_combined_raw.png")
t2["corr_comb"]  =  plot_t2("yield",    "pred_corr", "err_corr",
                              "Combined (corrected)", "fig2a_t2_combined_corr.png")
t2["raw_pv"]     =  plot_t2("yield_pv", "pred",      "err_raw_pv",
                              "P-V (raw)", "fig2b_t2_ss_raw.png")
t2["corr_pv"]    =  plot_t2("yield_pv", "pred_corr", "err_corr_pv",
                              "P-V (corrected)", "fig2b_t2_ss_corr.png")

# ────────────────────────────────────────────────────────
# Task 3: within-R² maps (state + mun)
# ────────────────────────────────────────────────────────
print("\n=== Task 3: within-R² state and mun maps ===")
def compute_r2_tables(ycol, pcol):
    d  =  df[df[ycol].notna() & df[pcol].notna()][["muncode", ycol, pcol]].copy()
    d["state"]  =  d["muncode"].str[:2]
    # state pooled within-R² (group by mun, demean, sum SS across muns in state)
    state_rows  =  []
    for st, g in d.groupby("state"):
        gm  =  g.groupby("muncode")[[ycol, pcol]].transform("mean")
        yd  =  g[ycol] - gm[ycol]
        yhd =  g[pcol] - gm[pcol]
        ss_tot  =  (yd ** 2).sum()
        ss_res  =  ((yd - yhd) ** 2).sum()
        state_rows.append({"state": st,
                           "within_r2": 1 - ss_res / ss_tot if ss_tot > 0 else np.nan,
                           "n_rows": len(g),
                           "n_mun":  g.muncode.nunique()})
    state_r2  =  pd.DataFrame(state_rows)
    state_r2["within_r2_plot"]  =  np.where(state_r2["n_rows"] >= MIN_ADCS_STATE,
                                              state_r2["within_r2"], np.nan)
    state_r2["within_r2_plot"]  =  state_r2["within_r2_plot"].clip(lower=R2_CLIP_LO)

    # mun within-R²
    mun_rows  =  []
    for mc, g in d.groupby("muncode"):
        if len(g) < MIN_ADCS_FOR_R2: continue
        ymean   =  g[ycol].mean()
        yhmean  =  g[pcol].mean()
        ss_tot  =  ((g[ycol] - ymean) ** 2).sum()
        ss_res  =  (((g[ycol] - ymean) - (g[pcol] - yhmean)) ** 2).sum()
        mun_rows.append({"muncode": mc,
                          "within_r2": 1 - ss_res / ss_tot if ss_tot > 0 else np.nan,
                          "n_rows": len(g),
                          "ss_tot": ss_tot,
                          "ss_res": ss_res,
                          "sd_obs": g[ycol].std(),
                          "sd_pred": g[pcol].std(),
                          "mean_obs":  ymean,
                          "mean_pred": yhmean,
                          "corr_obs_pred":
                            (np.corrcoef(g[ycol], g[pcol])[0, 1]
                             if g[ycol].std() > 0 and g[pcol].std() > 0
                             else np.nan),
                         })
    mun_r2  =  pd.DataFrame(mun_rows)
    return state_r2, mun_r2

def plot_state_mun_maps(state_r2, mun_r2, label, fname_state, fname_mun):
    states  =  gpd.read_file(state_shp).to_crs(epsg=4326)
    states["state"]  =  states["CVE_ENT"].astype(str).str.zfill(2)
    s_map  =  states.merge(state_r2, on="state", how="left")
    fig, ax  =  plt.subplots(figsize=(10, 8.5))
    norm  =  TwoSlopeNorm(vmin=-0.5, vcenter=0, vmax=0.5)
    s_map.plot(column="within_r2_plot", ax=ax, cmap="RdBu_r", norm=norm,
                legend=True, edgecolor="white", linewidth=0.6,
                missing_kwds={"color": "#d4d4d4"},
                legend_kwds={"label": f"Within-mun R² (≥{MIN_ADCS_STATE} rows)",
                             "shrink": 0.55})
    ax.set_axis_off()
    ax.set_title(f"{label}: within-mun R² by state")
    for _, row in s_map.iterrows():
        if pd.notna(row["within_r2_plot"]):
            x, y  =  row.geometry.representative_point().coords[0]
            ax.text(x, y, f"{row['within_r2_plot']:+.2f}",
                     ha="center", va="center", fontsize=7, color="black")
    plt.tight_layout()
    fig.savefig(os.path.join(out_dir, fname_state), bbox_inches="tight", dpi=160)
    plt.close(fig)

    mun_g  =  gpd.read_file(mun_shp).to_crs(epsg=4326)
    mp  =  mun_r2.copy()
    mp["within_r2"]  =  mp["within_r2"].clip(lower=R2_CLIP_LO)
    m_map  =  mun_g.merge(mp, on="muncode", how="left")
    fig, ax  =  plt.subplots(figsize=(13, 11))
    norm  =  TwoSlopeNorm(vmin=-0.5, vcenter=0, vmax=0.5)
    m_map.plot(column="within_r2", ax=ax, cmap="RdBu_r", norm=norm,
                legend=True, edgecolor="none",
                missing_kwds={"color": "#e5e5e5"},
                legend_kwds={"label": f"Within-mun R² (n≥{MIN_ADCS_FOR_R2} rows)",
                             "shrink": 0.55})
    states.boundary.plot(ax=ax, color="black", linewidth=0.45)
    ax.set_axis_off()
    ax.set_title(f"{label}: within-mun R² by municipality "
                  f"({len(mun_r2):,} muns)")
    plt.tight_layout()
    fig.savefig(os.path.join(out_dir, fname_mun), bbox_inches="tight", dpi=170)
    plt.close(fig)

t3  =  {}
for (yc, pc, key, lab) in [
    ("yield",    "pred",      "raw_comb",  "Combined (raw)"),
    ("yield",    "pred_corr", "corr_comb", "Combined (corrected)"),
    ("yield_pv", "pred",      "raw_pv",    "P-V (raw)"),
    ("yield_pv", "pred_corr", "corr_pv",   "P-V (corrected)")]:
    sr, mr  =  compute_r2_tables(yc, pc)
    t3[key]  =  {"state_r2": sr, "mun_r2": mr}
    fbase  =  f"fig3_{key}"
    plot_state_mun_maps(sr, mr, lab,
                         f"{fbase}_state.png", f"{fbase}_mun.png")
    sr.to_csv(os.path.join(out_dir, f"within_r2_state_{key}.csv"), index=False)
    mr.to_csv(os.path.join(out_dir, f"within_r2_mun_{key}.csv"), index=False)

# ────────────────────────────────────────────────────────
# Task 3b: within-R² vs irrigation share
# ────────────────────────────────────────────────────────
mun_irrig  =  (agland.groupby("muncode", as_index=False)
                      .agg(siap_irrig_area=("siap_irrig_area", "sum"),
                           siap_agland_area=("siap_agland_area", "sum")))
mun_irrig["irrig_share"]  =  (mun_irrig["siap_irrig_area"] /
                                mun_irrig["siap_agland_area"].replace(0, np.nan))

def plot_r2_vs_irrig(mun_r2_df, label, fname):
    d  =  mun_r2_df.merge(mun_irrig[["muncode", "irrig_share"]],
                            on="muncode", how="left")
    d  =  d[d["irrig_share"].notna()]
    d["within_r2_wins"]  =  d["within_r2"].clip(lower=R2_CLIP_LO, upper=1.0)
    r_pear  =  d[["irrig_share", "within_r2_wins"]].corr().iloc[0, 1]
    r_spear =  d[["irrig_share", "within_r2"]].corr(method="spearman").iloc[0, 1]
    bins  =  np.linspace(0, 1, 11)
    d["bin"]  =  pd.cut(d["irrig_share"], bins, include_lowest=True)
    agg  =  (d.groupby("bin", observed=True)
               .agg(med_r2=("within_r2", "median"),
                    p25=("within_r2", lambda s: s.quantile(0.25)),
                    p75=("within_r2", lambda s: s.quantile(0.75)),
                    mean_wins=("within_r2_wins", "mean"))
               .reset_index())
    agg["x"]  =  agg["bin"].apply(lambda b: 0.5 * (b.left + b.right))
    fig, ax  =  plt.subplots(1, 2, figsize=(13, 4.7))
    sizes  =  np.clip(np.sqrt(d["n_rows"].astype(float)), 2, 30)
    ax[0].scatter(d["irrig_share"], d["within_r2_wins"], s=sizes,
                   alpha=0.35, color="#3a78b0", edgecolor="none",
                   rasterized=True)
    ax[0].axhline(0, color="grey", lw=0.5)
    ax[0].set_xlabel("Mun irrigation share (SIAP)")
    ax[0].set_ylabel(f"Within-mun R² (clipped at {R2_CLIP_LO})")
    ax[0].set_ylim(R2_CLIP_LO - 0.1, 1.05)
    ax[0].set_title(f"{label}: within-R² vs irrigation share\n"
                     f"r = {r_pear:+.3f}, ρ = {r_spear:+.3f}, "
                     f"N = {len(d):,} muns")
    ax[1].axhline(0, color="grey", lw=0.5)
    ax[1].errorbar(agg["x"], agg["med_r2"],
                    yerr=[agg["med_r2"] - agg["p25"],
                          agg["p75"] - agg["med_r2"]],
                    fmt="o", color="#3a78b0", capsize=3, lw=1)
    ax[1].plot(agg["x"], agg["mean_wins"], "s--", color="#c44e52",
                ms=5, label="Mean (winsorized)")
    ax[1].legend(loc="lower right")
    ax[1].set_xlabel("Mun irrigation share (SIAP)")
    ax[1].set_ylabel("Within-mun R² (median ± IQR)")
    ax[1].set_title(f"{label}: by irrigation decile")
    plt.tight_layout()
    fig.savefig(os.path.join(out_dir, fname), bbox_inches="tight", dpi=150)
    plt.close(fig)
    return {"r": r_pear, "rho": r_spear, "n_muns": len(d)}

t3b  =  {}
for key in ["raw_comb", "corr_comb", "raw_pv", "corr_pv"]:
    t3b[key]  =  plot_r2_vs_irrig(t3[key]["mun_r2"], key,
                                    f"fig3e_t3b_{key}_irrig.png")

# ────────────────────────────────────────────────────────
# Task 5: drivers of mun-level within-R²
# ────────────────────────────────────────────────────────
print("\n=== Task 5: drivers of mun within-R² ===")
mun_drv  =  t3["raw_comb"]["mun_r2"].copy()
mun_drv  =  mun_drv.merge(mun_irrig[["muncode", "irrig_share"]],
                            on="muncode", how="left")
mun_drv  =  mun_drv.merge(mun_share[["muncode", "maize_share"]],
                            on="muncode", how="left")
# Geometry from the FULL ADC partition (all control areas, ex-ante --
# NOT restricted to ADCs that happen to have maize ground truth):
#   mean_ha_adc = mean hectares per ADC; n_adc_geo = # ADCs per municipality
mean_adc  =  (agland.groupby("muncode", as_index=False)
                     .agg(mean_ha_adc=("adc_area", "mean"),
                          n_adc_geo=("adc_area", "size")))
mun_drv  =  mun_drv.merge(mean_adc, on="muncode", how="left")
mun_drv["log_n"]         =  np.log(mun_drv["n_rows"].clip(lower=1))
mun_drv["log_n_adc_geo"] =  np.log(mun_drv["n_adc_geo"].clip(lower=1))
mun_drv["log_sd_obs"]    =  np.log(mun_drv["sd_obs"].clip(lower=1e-3))
mun_drv["log_mean_obs"]  =  np.log(mun_drv["mean_obs"].clip(lower=1e-3))
mun_drv["log_ss_tot"]    =  np.log(mun_drv["ss_tot"].clip(lower=1e-6))
mun_drv["log_mean_ha_adc"]  =  np.log(mun_drv["mean_ha_adc"].clip(lower=1e-3))
mun_drv["wr2_wins"]      =  mun_drv["within_r2"].clip(lower=R2_CLIP_LO, upper=1)

feats  =  [
    ("log_n",         "log(# INEGI rows per mun)"),
    ("log_sd_obs",    "log(SD of obs yield in mun)"),
    ("log_mean_obs",  "log(mean obs yield in mun)"),
    ("irrig_share",   "Irrig share (SIAP)"),
    ("maize_share",   "Maize share (SIAP)"),
    ("log_mean_ha_adc",  "log(mean ha per ADC)"),
    ("corr_obs_pred", "corr(obs, pred) within mun"),
    ("log_ss_tot",    "log(SS_tot of obs in mun)"),
]
fig, axes  =  plt.subplots(2, 4, figsize=(20, 9.5))
for ax_i, (col, lab) in zip(axes.flatten(), feats):
    d  =  mun_drv[mun_drv[col].notna()].copy()
    r_p  =  d[[col, "wr2_wins"]].corr().iloc[0, 1]
    r_s  =  d[[col, "within_r2"]].corr(method="spearman").iloc[0, 1]
    ax_i.scatter(d[col], d["wr2_wins"], s=np.sqrt(d["n_rows"]) * 1.0,
                  alpha=0.35, color="#3a78b0", edgecolor="none", rasterized=True)
    ax_i.axhline(0, color="grey", lw=0.5)
    ax_i.set_xlabel(lab)
    ax_i.set_ylabel("Within-mun R² (clipped −2)")
    ax_i.set_title(f"r = {r_p:+.3f}, ρ = {r_s:+.3f} (N = {len(d):,})")
plt.suptitle("What drives per-municipality within-R²? "
              "(AEF Hist Ens. RAW, INEGI 2022 maize combined)",
              y=1.005)
plt.tight_layout()
fig.savefig(os.path.join(out_dir, "fig5a_drivers_scatter.png"),
             bbox_inches="tight", dpi=140)
plt.close(fig)

# OLS with state FE
try:
    import statsmodels.api as sm
    ols  =  mun_drv.dropna(subset=["wr2_wins", "log_n", "log_sd_obs",
                                     "log_mean_obs", "irrig_share",
                                     "maize_share", "log_mean_ha_adc",
                                     "corr_obs_pred"]).copy()
    ols["state"]  =  ols["muncode"].str[:2].astype("category")
    X  =  ols[["log_n", "log_sd_obs", "log_mean_obs", "irrig_share",
                 "maize_share", "log_mean_ha_adc", "corr_obs_pred"]].astype(float)
    Xc  =  sm.add_constant(X)
    mod  =  sm.OLS(ols["wr2_wins"], Xc).fit(cov_type="HC1")
    X_fe  =  pd.concat([X, pd.get_dummies(ols["state"], drop_first=True,
                                            prefix="st", dtype=float)],
                         axis=1)
    X_fe  =  sm.add_constant(X_fe)
    mod_fe  =  sm.OLS(ols["wr2_wins"], X_fe).fit(cov_type="HC1")
    with open(os.path.join(out_dir, "drivers_ols.txt"), "w") as f:
        f.write("OLS: within-R²(clipped at -2) ~ mun features (HC1 SE)\n\n")
        f.write(str(mod.summary()) + "\n\n")
        f.write("With state FE (non-state coefs):\n")
        nonst  =  [c for c in mod_fe.params.index if not c.startswith("st_")]
        tab  =  pd.DataFrame({"coef": mod_fe.params[nonst],
                                "se":   mod_fe.bse[nonst],
                                "t":    mod_fe.tvalues[nonst],
                                "p":    mod_fe.pvalues[nonst]})
        f.write(tab.to_string())
        f.write("\n")
except Exception as e:
    print("statsmodels OLS skipped:", e)

mun_drv.to_csv(os.path.join(out_dir, "drivers_mun.csv"), index=False)

# ────────────────────────────────────────────────────────
# Task 4: ADC yield maps (raw + corrected + observed + 3-panel)
# ────────────────────────────────────────────────────────
print("\n=== Task 4: ADC yield maps ===")
adc_geo  =  gpd.read_file(adc_shp)[["adcid", "geometry"]].to_crs(epsg=4326)
states_g  =  gpd.read_file(state_shp).to_crs(epsg=4326)

# Apply correction at ADC level (use the per-mun shift implied by paper logic)
# Per-adc raw: pred_adc.pred. For correction, use planted-area-weighted mun pred,
# anchor to SIAP yield (same as eval). Recompute shift here.
siap_22m  =  pd.read_stata(siap_szn)
siap_22m  =  siap_22m[(siap_22m["name"] == "Maize") & (siap_22m["year"] == YEAR)].copy()
siap_22m  =  siap_22m[~siap_22m["muncode"].str.endswith("000")]
siap_mun  =  (siap_22m.groupby("muncode")
                       .agg(q=("q", "sum"), ha=("ha_planted", "sum"))
                       .reset_index())
siap_mun["yield_siap"]  =  siap_mun["q"] / siap_mun["ha"]
siap_mun  =  siap_mun[siap_mun["yield_siap"].notna()
                       & (siap_mun["yield_siap"] > 0)][["muncode", "yield_siap"]]

# Use df-based shifts (paper's exact logic): mun avg pred − siap yield
df_for_shift  =  df.copy()
df_for_shift["wQ"]  =  df_for_shift["pred"] * df_for_shift["land_input"]
df_for_shift["wA"]  =  np.where(np.isfinite(df_for_shift["pred"]),
                                  df_for_shift["land_input"], 0)
shift_tbl  =  (df_for_shift.groupby("muncode")
                            .agg(wQ=("wQ", "sum"), wA=("wA", "sum"))
                            .reset_index())
shift_tbl["pred_mun_avg"]  =  shift_tbl["wQ"] / shift_tbl["wA"]
shift_tbl  =  shift_tbl.merge(siap_mun, on="muncode", how="left")
shift_tbl["shift"]  =  shift_tbl["pred_mun_avg"] - shift_tbl["yield_siap"]

pred_adc  =  pred_adc.merge(shift_tbl[["muncode", "shift"]], on="muncode", how="left")
pred_adc["pred_corr"]  =  (pred_adc["pred"] - pred_adc["shift"]).clip(lower=0)
pred_adc.loc[pred_adc["shift"].isna(), "pred_corr"]  =  np.nan

# Raw map
adc_raw_map  =  adc_geo.merge(pred_adc[["adcid", "pred"]], on="adcid", how="left")
adc_raw_map["y_plot"]  =  adc_raw_map["pred"].clip(lower=0, upper=10)
fig, ax  =  plt.subplots(figsize=(14, 11))
adc_raw_map.plot(column="y_plot", ax=ax, cmap="YlGn", linewidth=0,
                  vmin=0, vmax=8, legend=True,
                  missing_kwds={"color": "#e8e8e8"},
                  legend_kwds={"label": "Predicted maize yield (t/ha)",
                               "shrink": 0.6})
states_g.boundary.plot(ax=ax, color="#222", linewidth=0.45)
ax.set_axis_off()
ax.set_title("AEF Hist Ens. — RAW 2022 predicted maize yield, ADC-level\n"
              f"({adc_raw_map['pred'].notna().sum():,}/{len(adc_geo):,} ADCs)")
plt.tight_layout()
fig.savefig(os.path.join(out_dir, "fig4_adc_yield_map.png"),
             bbox_inches="tight", dpi=170)
plt.close(fig)

# Corrected map
adc_corr_map  =  adc_geo.merge(pred_adc[["adcid", "pred_corr"]],
                                 on="adcid", how="left")
adc_corr_map["y_plot"]  =  adc_corr_map["pred_corr"].clip(lower=0, upper=10)
fig, ax  =  plt.subplots(figsize=(14, 11))
adc_corr_map.plot(column="y_plot", ax=ax, cmap="YlGn", linewidth=0,
                   vmin=0, vmax=8, legend=True,
                   missing_kwds={"color": "#e8e8e8"},
                   legend_kwds={"label": "Predicted (SIAP-anchored) yield (t/ha)",
                                "shrink": 0.6})
states_g.boundary.plot(ax=ax, color="#222", linewidth=0.45)
ax.set_axis_off()
ax.set_title("AEF Hist Ens. — additive-corrected 2022 predicted maize yield, ADC-level\n"
              f"({adc_corr_map['pred_corr'].notna().sum():,}/{len(adc_geo):,} ADCs)")
plt.tight_layout()
fig.savefig(os.path.join(out_dir, "fig4d_adc_yield_map_corrected.png"),
             bbox_inches="tight", dpi=170)
plt.close(fig)

# Observed map — INEGI 2022 maize yield aggregated to ADC (planted-area weighted)
gt_for_map  =  (df.groupby(["muncode"])
                    .apply(lambda g: g, include_groups=False))  # placeholder
# Aggregate INEGI to one (adc) row using planted-area-weighted mean
inegi_adc  =  (df.dropna(subset=["yield"])
                  .assign(wQ=lambda x: x["yield"] * x["land_input"],
                          wA=lambda x: x["land_input"])
                  .groupby("adc")
                  .agg(wQ=("wQ", "sum"), wA=("wA", "sum"))
                  .reset_index())
inegi_adc["y_obs"]  =  inegi_adc["wQ"] / inegi_adc["wA"]
adc_geo["adc"]  =  adc_geo["adcid"].str.replace("-", "", regex=False)
obs_map  =  adc_geo.merge(inegi_adc[["adc", "y_obs"]], on="adc", how="left")
obs_map["y_plot"]  =  obs_map["y_obs"].clip(lower=0, upper=10)

fig, ax  =  plt.subplots(figsize=(14, 11))
obs_map.plot(column="y_plot", ax=ax, cmap="YlGn", linewidth=0,
              vmin=0, vmax=8, legend=True,
              missing_kwds={"color": "#e8e8e8"},
              legend_kwds={"label": "Observed maize yield (t/ha, INEGI 2022)",
                           "shrink": 0.6})
states_g.boundary.plot(ax=ax, color="#222", linewidth=0.45)
ax.set_axis_off()
matched_obs  =  obs_map["y_obs"].notna().sum()
ax.set_title(f"INEGI 2022 — observed maize yield, ADC-level\n"
              f"(matched {matched_obs:,}/{len(adc_geo):,} ADCs)")
plt.tight_layout()
fig.savefig(os.path.join(out_dir, "fig4b_adc_yield_map_inegi.png"),
             bbox_inches="tight", dpi=170)
plt.close(fig)

# 3-panel
fig, axes  =  plt.subplots(1, 3, figsize=(26, 9))
for ax_i, (gdf, ttl) in zip(
    axes,
    [(adc_raw_map,  "Predicted — raw"),
     (adc_corr_map, "Predicted — additive-corrected"),
     (obs_map,      "Observed (INEGI 2022)")]):
    gdf.plot(column="y_plot", ax=ax_i, cmap="YlGn", linewidth=0,
              vmin=0, vmax=8, missing_kwds={"color": "#e8e8e8"})
    states_g.boundary.plot(ax=ax_i, color="#222", linewidth=0.4)
    ax_i.set_axis_off()
    ax_i.set_title(ttl, fontsize=12)
sm  =  mpl.cm.ScalarMappable(cmap="YlGn",
                              norm=mpl.colors.Normalize(vmin=0, vmax=8))
fig.colorbar(sm, ax=axes, shrink=0.55, fraction=0.025, pad=0.02
              ).set_label("Maize yield (t/ha)")
fig.suptitle("ADC-level maize yield: AEF Hist Ens. raw / corrected vs INEGI 2022",
              fontsize=13, y=0.96)
fig.savefig(os.path.join(out_dir, "fig4c_adc_yield_compare.png"),
             bbox_inches="tight", dpi=170)
plt.close(fig)

# ────────────────────────────────────────────────────────
# Summary stats
# ────────────────────────────────────────────────────────
with open(os.path.join(out_dir, "summary_stats.txt"), "w") as f:
    f.write("Coauthor extras — AEF Hist Ens. (paper-aligned eval)\n")
    f.write(f"Year: {YEAR}\n\n")
    f.write("Task 1 — maize share vs |ADC err|:\n")
    for k, v in t1.items():
        f.write(f"  {k:<10s}: r(|err|)={v['r_abs']:+.4f}  "
                 f"ρ={v['spearman_abs']:+.4f}  "
                 f"r(signed)={v['r_signed']:+.4f}  N={v['n']:,}\n")
    f.write("\nTask 2 — ADC err vs mun err:\n")
    for k, v in t2.items():
        f.write(f"  {k:<10s}: r(INEGI)={v['r_inegi']:+.4f}  "
                 f"r(SIAP)={v['r_siap']:+.4f}  "
                 f"ρ(INEGI)={v['rho_inegi']:+.4f}  N={v['n']:,}\n")
    f.write("\nTask 3 — state pooled within-R²:\n")
    for k in ["raw_comb", "corr_comb", "raw_pv", "corr_pv"]:
        sr  =  t3[k]["state_r2"]
        f.write(f"  {k:<10s}: mean={sr['within_r2_plot'].mean():+.4f}  "
                 f"median={sr['within_r2'].median():+.4f}  "
                 f"N={len(sr):,}\n")
    f.write("\nTask 3 — mun within-R² (winsorized at -2):\n")
    for k in ["raw_comb", "corr_comb", "raw_pv", "corr_pv"]:
        mr  =  t3[k]["mun_r2"]
        ww  =  mr["within_r2"].clip(lower=R2_CLIP_LO)
        f.write(f"  {k:<10s}: mean_wins={ww.mean():+.4f}  "
                 f"median={mr['within_r2'].median():+.4f}  "
                 f"p25={mr['within_r2'].quantile(0.25):+.4f}  "
                 f"p75={mr['within_r2'].quantile(0.75):+.4f}  "
                 f"N={len(mr):,}\n")
    f.write("\nTask 3b — within-R² vs irrigation share:\n")
    for k, v in t3b.items():
        f.write(f"  {k:<10s}: r={v['r']:+.4f}  ρ={v['rho']:+.4f}  "
                 f"N_mun={v['n_muns']:,}\n")
    f.write("\nTask 4 — ADC yield maps:\n")
    f.write(f"  raw matched:       "
             f"{adc_raw_map['pred'].notna().sum():,}/{len(adc_geo):,}\n")
    f.write(f"  corrected matched: "
             f"{adc_corr_map['pred_corr'].notna().sum():,}/{len(adc_geo):,}\n")
    f.write(f"  obs matched:       "
             f"{obs_map['y_obs'].notna().sum():,}/{len(adc_geo):,}\n")
    f.write(f"  raw yield (t/ha): "
             f"mean={adc_raw_map['pred'].mean():.2f}  "
             f"median={adc_raw_map['pred'].median():.2f}\n")
    f.write(f"  corrected yield (t/ha): "
             f"mean={adc_corr_map['pred_corr'].mean():.2f}  "
             f"median={adc_corr_map['pred_corr'].median():.2f}\n")
    f.write(f"  observed yield (t/ha): "
             f"mean={obs_map['y_obs'].mean():.2f}  "
             f"median={obs_map['y_obs'].median():.2f}\n")
print(f"\nAll outputs → {out_dir}")
